In [1]:
from transformers.models.vit.configuration_vit import ViTConfig

e:\CV\Middle_Test\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
config = ViTConfig()

In [3]:
(1, ) + (2, )

(1, 2)

In [4]:
config

ViTConfig {
  "attention_probs_dropout_prob": 0.0,
  "encoder_stride": 16,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 768,
  "image_size": 224,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "model_type": "vit",
  "num_attention_heads": 12,
  "num_channels": 3,
  "num_hidden_layers": 12,
  "patch_size": 16,
  "qkv_bias": true,
  "transformers_version": "4.38.1"
}

In [5]:
from transformers.activations import ACT2FN
ACT2FN["gelu"]

GELUActivation()

In [6]:
from model.embedding import ViTEmbeddings
import torch
import cv2
from model.attention import ViTSelfAttention


In [7]:
embedding = ViTEmbeddings(config)

In [8]:
image = cv2.imread("./image/cat1.jpg")

In [9]:
image = cv2.resize(image, (224, 224))

In [10]:
input = torch.tensor(image).unsqueeze(0).transpose(1, 3).float()

In [11]:
image_embb = embedding(input)

In [12]:
selfattention = ViTSelfAttention(config)

In [13]:
image_embb.shape

torch.Size([1, 197, 768])

In [14]:
selfattention(image_embb)

(tensor([[[-5.5765e-01,  2.2365e+01,  1.1502e+02,  ..., -5.8481e+01,
           -2.2794e+01,  1.6128e+01],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8238e+01,
           -3.2002e+01,  6.7432e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -3.9004e+01,
           -2.0669e-01,  2.2382e+01],
          ...,
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00]]], grad_fn=<ViewBackward0>),)

In [15]:
import torch

# Tạo một tensor không liên tục
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = x[:, 1]  # Thực hiện phép cắt

print(x.is_contiguous())  # False, không liên tục
print(y.is_contiguous())  # False, không liên tục
print(y)
# Sử dụng contiguous() để tạo một tensor liên tục
y = x[:, 1].contiguous()

print(y.is_contiguous())  # True, liên tục


True
False
tensor([2, 5])
True


In [16]:
y

tensor([2, 5])

In [17]:
from model.model import ViTModel

In [18]:
model = ViTModel(config=config)

In [21]:
model(input).pooler_output.shape

torch.Size([1, 768])

In [22]:
config

ViTConfig {
  "attention_probs_dropout_prob": 0.0,
  "encoder_stride": 16,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 768,
  "image_size": 224,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "model_type": "vit",
  "num_attention_heads": 12,
  "num_channels": 3,
  "num_hidden_layers": 12,
  "patch_size": 16,
  "qkv_bias": true,
  "transformers_version": "4.38.1"
}

In [23]:
import json
with open("config.json", 'r') as file:
    config = json.load(file)

In [25]:
config['config_model']['num_classes']

5