In [1]:
from transformers.models.vit.configuration_vit import ViTConfig

e:\CV\Middle_Test\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
config = ViTConfig()

In [3]:
(1, ) + (2, )

(1, 2)

In [4]:
config

ViTConfig {
  "attention_probs_dropout_prob": 0.0,
  "encoder_stride": 16,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 768,
  "image_size": 224,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "model_type": "vit",
  "num_attention_heads": 12,
  "num_channels": 3,
  "num_hidden_layers": 12,
  "patch_size": 16,
  "qkv_bias": true,
  "transformers_version": "4.38.1"
}

In [5]:
from transformers.activations import ACT2FN
ACT2FN["gelu"]

GELUActivation()

In [6]:
from model.embedding import ViTEmbeddings
import torch
import cv2
from model.attention import ViTSelfAttention


In [7]:
embedding = ViTEmbeddings(config)

In [8]:
image = cv2.imread("./image/cat1.jpg")

In [9]:
image = cv2.resize(image, (224, 224))

In [10]:
input = torch.tensor(image).unsqueeze(0).transpose(1, 3).float()

In [11]:
image_embb = embedding(input)

In [12]:
selfattention = ViTSelfAttention(config)

In [13]:
image_embb.shape

torch.Size([1, 197, 768])

In [14]:
selfattention(image_embb)

(tensor([[[-5.5765e-01,  2.2365e+01,  1.1502e+02,  ..., -5.8481e+01,
           -2.2794e+01,  1.6128e+01],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8238e+01,
           -3.2002e+01,  6.7432e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -3.9004e+01,
           -2.0669e-01,  2.2382e+01],
          ...,
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00],
          [ 1.5282e+00,  5.3770e+01,  2.4847e+02,  ..., -5.8239e+01,
           -3.2002e+01,  6.7430e+00]]], grad_fn=<ViewBackward0>),)

In [15]:
import torch

# Tạo một tensor không liên tục
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = x[:, 1]  # Thực hiện phép cắt

print(x.is_contiguous())  # False, không liên tục
print(y.is_contiguous())  # False, không liên tục
print(y)
# Sử dụng contiguous() để tạo một tensor liên tục
y = x[:, 1].contiguous()

print(y.is_contiguous())  # True, liên tục


True
False
tensor([2, 5])
True


In [16]:
y

tensor([2, 5])

In [17]:
from model.model import ViTModel

In [18]:
model = ViTModel(config=config)

In [20]:
model(input).pooler_output

tensor([[ 7.1060e-01,  1.0064e-01, -3.2487e-01, -4.5797e-01,  7.8438e-01,
         -7.5106e-01,  5.7990e-01, -2.0085e-02,  3.3337e-01,  2.4429e-01,
         -7.5710e-01, -6.4561e-01,  4.1990e-01, -8.0800e-01,  5.4772e-01,
          5.6939e-01, -1.1429e-01,  3.7180e-01, -7.2423e-01,  5.7131e-01,
         -2.6326e-01,  1.0750e-01, -4.2335e-01, -4.8489e-01, -7.5983e-01,
         -4.0176e-01,  4.7974e-01, -1.7467e-01, -1.1818e-02,  4.6869e-01,
         -8.8047e-02, -1.8706e-01,  2.8802e-01,  7.5349e-01,  4.8461e-01,
         -1.3052e-01, -8.0056e-01,  5.7192e-01,  1.3439e-01, -2.5401e-01,
          5.8764e-01, -1.8702e-02, -5.9909e-01,  7.0225e-02,  7.0422e-02,
          1.0014e-01,  6.7562e-01,  1.8252e-01,  4.6469e-01, -1.5140e-01,
         -4.6640e-04,  3.9167e-01, -6.5252e-01,  1.0032e-01, -2.4911e-01,
         -6.7385e-01, -9.6884e-03, -4.7219e-01,  3.6203e-02,  1.6474e-01,
          4.8201e-01, -5.1821e-04,  3.1251e-01,  2.4903e-01,  3.5625e-02,
         -7.2837e-01,  3.6921e-01, -8.